# Generated by Django 5.0.1 on 2024-01-31 21:36

import django.contrib.gis.db.models.fields
import z.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('z', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, validators=[z.models.is_valid_point]),
        ),
    ]
