# Generated by Django 5.0.1 on 2024-01-31 23:21

import django.contrib.gis.db.models.fields
import django.core.validators
import z.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z', '0002_alter_treasure_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='treasure',
            name='status',
            field=models.IntegerField(choices=[(0, 'Posted'), (1, 'Received'), (2, 'Found')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='description',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
