# Generated by Django 5.0.1 on 2024-02-01 12:56

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z', '0003_treasure_photo_treasure_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_default=models.Value(True))),
            ],
        ),
        migrations.DeleteModel(
            name='treasure'
        )
    ]
