# Generated by Django 5.0.1 on 2024-02-01 13:05

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.functions.datetime
import uuid
import z.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z', '0004_token_treasure_date_posted_alter_treasure_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, validators=[z.models.is_valid_point])),
                ('description', models.TextField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('date_posted', models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), editable=False)),
                ('status', models.IntegerField(choices=[(0, 'Posted'), (1, 'Received'), (2, 'Found')], default=0, editable=False)),
            ],
        ),
    ]
