# Generated by Django 5.0.1 on 2024-03-05 14:39

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z', '0005_treasure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='photo',
        ),
        migrations.AlterField(
            model_name='treasure',
            name='date_posted',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='')),
                ('treasure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='z.treasure')),
            ],
        ),
    ]
