# Generated by Django 5.0.1 on 2024-03-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z', '0006_remove_treasure_photo_alter_treasure_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='new',
            field=models.BooleanField(db_default=models.Value(True)),
        ),
    ]
